#some tips: http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
site_name: Qi Docs
site_description: Documenation for the Qi service
site_favicon: '/img/qi-docs-favicon.ico'
<<<<<<< HEAD
copyright: Copyright &copy; 2016, OSIsoft, LLC
=======
copyright: Copyright &copy; 2015, OSIsoft, LLC <style type="text/css">.wy-nav-content-wrap{Background:none!important;}</style>
>>>>>>> refs/remotes/origin/master
docs_dir: docs
repo_url: https://github.com/osisoft/Qi-Docs
# theme: sphinx_rtd_theme

pages:
- Introduction: 'index.md'
- API reference: #'Qi Service API Reference.md'
  - Overview: 'Overview.rst'
  - QiTypes: 'QiTypes.rst'
  - QiStreams: 'QiStreams.rst'
  - QiStreamBehaviors: 'QiStreamBehaviors.rst'
  - Searching for QiStreams: 'Searching.rst'
  - Writing data: 'Writing data.rst'
  - Reading data: 'Reading data.rst'
  - Filter expressions: 'Filter Expressions.rst'
- Samples:  'samples.rst'
- Preview: 'preview.rst'
- Support:  'support.rst'
